Args=--initialize-at-run-time=org.graalvm.shadowed.com.ibm.icu \
--initialize-at-build-time=org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2$1,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2$CharSequenceIterator,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2$Range,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2$Trie2Header,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2$Trie2Iterator,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2$UTrie2Header,\
org.graalvm.shadowed.com.ibm.icu.impl.Trie2_16,\
org.graalvm.shadowed.com.ibm.icu.impl.UCaseProps,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$1,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$2,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$3,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$4,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$5,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$6,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$7,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$8,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$9,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$10,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$11,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$12,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$13,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$14,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$15,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$16,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$17,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$18,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$19,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$20,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$21,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$22,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$23,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$24,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$25,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$26,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$27,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$28,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$29,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$30,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$BinaryProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$CaseBinaryProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$EmojiBinaryProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$IntProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$MathCompatBinaryProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$MCMBinaryProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$NormInertBinaryProperty,\
org.graalvm.shadowed.com.ibm.icu.impl.UCharacterProperty$NormQuickCheckIntProperty,\
org.graalvm.shadowed.com.ibm.icu.lang.UCharacter,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Data,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Data16,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Data32,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Data8,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Fast,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Fast$FastStringIterator,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Fast16,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Fast32,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Fast8,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Small,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Small$SmallStringIterator,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Small16,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Small32,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Small8,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$Type,\
org.graalvm.shadowed.com.ibm.icu.util.CodePointTrie$ValueWidth,\
org.graalvm.shadowed.com.ibm.icu.util.VersionInfo \
--features=org.graalvm.shadowed.com.ibm.icu.ICU4JFeature
