[[rule]]
files = ["CEntryPointSnippets.java", "EarlyProcessWideState.java", "GCAllocationSupport.java", "SafepointSnippets.java", "SubstrateAllocationSnippets.java"]
all = [
    "christian.haeubl@oracle.com",
]
any = [
]
