/*
 * Copyright (c) 2026, 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * The Universal Permissive License (UPL), Version 1.0
 *
 * Subject to the condition set forth below, permission is hereby granted to any
 * person obtaining a copy of this software, associated documentation and/or
 * data (collectively the "Software"), free of charge and under any and all
 * copyright rights in the Software, and any and all patent rights owned or
 * freely licensable by each licensor hereunder covering either (i) the
 * unmodified Software as contributed to or provided by such licensor, or (ii)
 * the Larger Works (as defined below), to deal in both
 *
 * (a) the Software, and
 *
 * (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
 * one is included with the Software each a "Larger Work" to which the Software
 * is contributed by such licensors),
 *
 * without restriction, including without limitation the rights to copy, create
 * derivative works of, display, perform, and distribute the Software and make,
 * use, sell, offer for sale, import, export, have made, and have sold the
 * Software and the Larger Work(s), and to sublicense the foregoing rights on
 * either these or other terms.
 *
 * This license is subject to the following condition:
 *
 * The above copyright notice and either this complete permission notice or at a
 * minimum a reference to the UPL must be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.oracle.truffle.polyglot.isolate;

import java.lang.reflect.Constructor;
import java.lang.reflect.Executable;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.ServiceLoader;

import org.graalvm.jniutils.JNIEntryPoint;
import org.graalvm.jniutils.JNIEntryPointProvider;
import org.graalvm.nativeimage.AnnotationAccess;
import org.graalvm.nativeimage.ImageSingletons;
import org.graalvm.nativeimage.Platform;
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeJNIAccess;

/**
 * A feature enabling the host part of the Truffle isolate support. The Truffle isolate support
 * consists of the host and guest part. The host part contains polyglot API entry points and support
 * for host types. The guest part is an isolate with guest languages. This feature registers the
 * {@link JNIEntryPoint}-annotated methods generated by the native bridge processor and the
 * {@link PolyglotIsolateHostFeatureEnabled} instance into {@link ImageSingletons}. The polyglot
 * isolate code can use {@link ImageSingletons#contains(Class)
 * ImageSingletons.contains(PolyglotIsolateHostFeatureEnabled.class)} to prevent substratevm from
 * including methods that should not be reachable on the host side.
 * <p>
 * The JNI entry point registration is intentionally kept in this Truffle-specific feature even
 * though it would be cleaner architecturally to register them in a separate feature in the
 * {@code org.graalvm.jniutils} module. Libgraal builds using a legacy GraalVM place
 * {@code org.graalvm.jniutils} on the module path while Truffle is in the GraalVM jimage. In that
 * layout a generic JNI entry point feature would discover Truffle providers from the jimage and
 * make Truffle reachable in libgraal, which must not happen. Once the legacy builds are removed,
 * the JNI entry point registration can be split back into a separate feature in
 * {@code org.graalvm.jniutils}.
 *
 * @see PolyglotIsolateHostFeatureEnabled
 */
final class PolyglotIsolateHostFeature implements Feature {

    @Override
    public boolean isInConfiguration(IsInConfigurationAccess access) {
        // Do not enable polyglot isolate in web-image
        return Platform.includedIn(Platform.LINUX.class) || Platform.includedIn(Platform.DARWIN.class) || Platform.includedIn(Platform.WINDOWS.class);
    }

    @Override
    public void afterRegistration(AfterRegistrationAccess access) {
        ImageSingletons.add(PolyglotIsolateHostFeatureEnabled.class, new PolyglotIsolateHostFeatureEnabled());
    }

    @Override
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        try {
            registerNativeMethods(access);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException("Failed to register JNI entry points.", e);
        }
    }

    @Override
    public String getDescription() {
        return "Provides polyglot host isolate embedding support";
    }

    private static void registerNativeMethods(BeforeAnalysisAccess access) throws ReflectiveOperationException {
        for (JNIEntryPointProvider registration : ServiceLoader.load(JNIEntryPointProvider.class, access.getApplicationClassLoader())) {
            Class<?> annotatedClass = Class.forName(registration.getClassName(), false, registration.getClass().getClassLoader());
            List<Executable> classExecutables = findAnnotatedMethods(annotatedClass);
            if (!classExecutables.isEmpty()) {
                RuntimeJNIAccess.register(annotatedClass);
                classExecutables.forEach(RuntimeJNIAccess::register);
            }
        }
    }

    private static List<Executable> findAnnotatedMethods(Class<?> annotatedClass) {
        List<Executable> result = new ArrayList<>();
        for (Method method : annotatedClass.getDeclaredMethods()) {
            if (AnnotationAccess.getAnnotation(method, JNIEntryPoint.class) != null) {
                result.add(method);
            }
        }
        for (Constructor<?> constructor : annotatedClass.getDeclaredConstructors()) {
            if (AnnotationAccess.getAnnotation(constructor, JNIEntryPoint.class) != null) {
                result.add(constructor);
            }
        }
        return result;
    }
}
